n = int(input('Digite um número:'))
print('{} x {:2} = {}'.format(n,0,n*0))
print('{} x {} = {}'.format(n,1,n*1))
print('{} x {} = {}'.format(n,2,n*2))
print('{} x {} = {}'.format(n,3,n*3))
print('{} x {} = {}'.format(n,4,n*4))
print('{} x {} = {}'.format(n,5,n*5))
print('{} x {} = {}'.format(n,6,n*6))
