lista = ('Lápis', 1.75, 'Borracha', 2, 'Caderno', 15.90, 'Estojo', 25, 'Transferidor', 4.20)
print('-'*44)
print('           TABELA DE PREÇOS')
print('-'*44)
print(f'{lista[0]}', end='...............................')
print(f'R$  {lista[1]}')
print(f'{lista[2]}', end='............................')
print(f'R$  {lista[3]:.2f}')
print(f'{lista[4]}', end='.............................')
print(f'R$ {lista[5]:.2f}')
print(f'{lista[6]}', end='..............................')
print(f'R$ {lista[7]:.2f}')
print('-'*44)
